# This Cloud Build configuration file defines the steps required to
# build a Docker image, push it to Artifact Registry, and then
# deploy it to Cloud Run.
  
steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-northeast1-docker.pkg.dev/testprojectcicd-430610/quickstart-docker-repo/myimage:$REVISION_ID'
    - 'asia-northeast1-docker.pkg.dev/testprojectcicd-430610/quickstart-docker-repo/myimage:latest'
    - '.'

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-northeast1-docker.pkg.dev/testprojectcicd-430610/quickstart-docker-repo/myimage:$REVISION_ID'

# Deploy to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - 'run'
#     - 'deploy'
#     - 'my-service'  # place-holder
#     - '--image'
#     - $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
#     - '--allow-unauthenticated'   

 
options:
  logging: 'CLOUD_LOGGING_ONLY'
